name: build
on:
  workflow_dispatch:
   
  push:
    branches:
      - 'dev'
      - 'test'
      - 'main' 
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    steps:      

      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # SDK Version to use.
      - name: set_nuget_sourse
        run: dotnet nuget add source https://pkgs.dev.azure.com/ECCODevOps/ECCO-Integration/_packaging/IntAzNuget/nuget/v3/index.json --username dummy --password ${{ secrets.NUGET_PWD }} --store-password-in-clear-text --name tnuget 
         
      - run: dotnet build --configuration Release integration.services.rabbitmq.producer/Ecco.Integrations.RabbitMq.Producer.Service/Ecco.Integrations.RabbitMq.Producer.Service.csproj